- String/String Reversal/README.md
> String Reversal

- String/Pangrams/README.md
- String/Pangrams/solution.cpp
Created a new folder called "Pangrams" inside the "Strings" folder and added the question as "README.md". Please merge this.
> Added a new question "Pangrams" to the String folder.

- Linked Lists/Check a linked list palindrome or not
- Linked Lists/Linked list palindrome or not
- Linked Lists/Palindrome linked list/Check a linked list palindrome or not
- Linked Lists/Palindrome linked list/README.md
Adding a program linked list palindrome
> Linked list palindrome

- String/Pangrams/solution.cpp
Removed the redundant lines in String\Pangrams\solution.cpp as in #35
> Removed the redundant lines in solution.cpp

- Array/Find the Duplicate Number/main.py
> Replacing range and len with enumerate() method

- Math/MillerRabbin_PrimalityTest/MillerRabbin.cpp
- Math/MillerRabbin_PrimalityTest/README.md
Miller rabbin primality test helps in finding a number is prime or not in logN complexity
> Miller Rabbin Primality Test Added in Math section

- String/String Reversal/reverse_string.cpp
> fix: Redundant line at start of code block #41

- Array/Rearrange_array/Rearrange_array.java
Fixed 'The name of the outer type and the file do not match.' issue in Array\Rearrange_array\Rearrange_array.java #34
> Name of the class fixed

- deque/PLayWIthSTL/Solution.cpp
> Removed blank line at start of code block

- String/Pangrams/solution.cpp
> Removed redundant lines

- Graph/Tarjans_Algorithm/README.md
- Graph/Tarjans_Algorithm/Tarjans_Algorithm.cpp
Added C++ code of Tarjan's Algorithm and its corresponding README.
Issue : #68
> Added tarjan's Algorithm.

- Dynamic Programming/TarjanAlgo/README.md
- Dynamic Programming/TarjanAlgo/Tarjan.c
This Fixes #68 
Hacktoberfest 2021
> Implementation of Tarjan's Algorithm

- Array/First Repeating Element/solution.cpp
- BackTracking/WellFormedParanthesis/main.cpp
- Stack/Maximum Rectangular Area in a Histogram/Maximum_Rectangular_Area_in_Histogram.cpp
- Stack/Stock_span/Stock_span.cpp
- String/Pangrams/solution.cpp
- deque/PLayWIthSTL/Solution.cpp
#27 
#28 
#29 
#30 
#32 
#37 
#42
> Fixed all redundant blank spaces

- Dynamic Programming/01-Knapsack/01_Knapsackproblem.cpp
- Dynamic Programming/01-Knapsack/ReadME.md
Hello, Here I am giving a little contribution to Dynamic programming. I have done Knapsack_Problem in C++ using dynamic programming. Hope you will find it helpful.
<hr>
<hr>
- DSA
- Dynamic Programming
- C++
- Greedy
- Matrix
<hr>
I'm giving my contribution in Dynamic Programming so that others can motivate by it and learn from it. Happy coding.
Thank you 😊.
> Knapsack_Problem_DP

- Array/Add to Array-Form of Integer/Add to Array-Form of Integer.cpp
- Array/Add to Array-Form of Integer/Readme.md
added **Add to Array Form of Integer** program in array folder 
[Add to Array Form of Integer](https://leetcode.com/problems/add-to-array-form-of-integer/)
plzz label it with Hackerfest2021 :))
> added add to array form of integer program

- Array/Rearrange_array/Rearrange.java
- Array/Rearrange_array/Rearrange_array.java
- Array/Search in Rotated Sorted Array/README.md
- Array/Search in Rotated Sorted Array/Solution.java
1) Fixed 'Top-level class Rearrange has to reside in its own source file.' issue in Array\Rearrange_array\Rearrange_array.java #33 and created new file for class Rearrange.
2) Also, added new program "Search in Rotated Sorted Array" with proper solution and explanation. Also followed the contributing guidelines for this repo.
> Fixed class issue, Also added new program

- Searching/Count the number of ANAGRAMS/readme.md
- Searching/Count the number of ANAGRAMS/solution.cpp
Greetings!
This is Sundar. I have written a code for counting the number of ANAGRAMS.
Hope you like it and merge it with your project / repository and consider this as my contribution for 
HACKTOBERFEST-2021 .
> Count the number of ANAGRAMS

- Linked Lists/deleting_middle_element_of_LL/README.md
- Linked Lists/deleting_middle_element_of_LL/delete_middle_of_LL.cpp
the following program deletes the middle of the linked list.
> delete middle of Linked List

- Dynamic Programming/Jump Game 2/README.md
- Dynamic Programming/Jump Game 2/solution.cpp
Added a Dynamic Programming problem from Leetcode.
> Added a new Dynamic Programming Question

- Math/PerfectCube/Perfectcube.cpp
- Math/PerfectCube/Readme.md
Changes into Perfectcube of Math folder.
> Lokesh Gawande

- Queue/Reveal Cards in Increasing Order/readme.md
- Queue/Reveal Cards in Increasing Order/solution.cpp
Added a Program in Queues
Problem Name : Reveal Cards In Increasing Order
1. Added Detailed problem readme with explanation and approach.
2. Added optimized solution.
Thanks in Advance ✨.
> queues / reveal cards in increasing order

- Array/Sorted Squared Array/README.md
- Array/Sorted Squared Array/main.py
Sorted Squared Array solution main file and readme file added.
> Sorted Squared Array

- Binary Tree/BST operations/Binary_Search_Tree_operations.cpp
- Binary Tree/BST operations/README.md
Added code for the issue #103 code for operations on Binary search tree.
> Added code for operations on Binary search tree

- Binary Tree/Threaded Binary Tree/README.md
- Binary Tree/Threaded Binary Tree/Threaded_Binary_Tree.cpp
Added code for the issue #105 code for operations on Threader Binary tree
> Added code for threaded binary tree

- Array/Wave_Sort_Array/README.md
- Array/Wave_Sort_Array/wave_array.cpp
Hi! I have added the wave sort array program to the issue "Adding new programs and their solutions. #70"...I have created the folder Wave_Sort_Array inside the array folder in the repo and within that folder, I have included one c++ source code file and the README.md file describing the working of the code. Please if you like my code then please merge my PR to your repo. Thank you.
> added the wave sort array program alongwith the README.md file.

- Dynamic Programming/Tribonacci Number/README.md
- Dynamic Programming/Tribonacci Number/main.py
- String/Roman to Integer/README.md
- String/Roman to Integer/main.py
Solution and description of problem added.
> Roman to Integer

- Linked Lists/Rotate List/README.md
- Linked Lists/Rotate List/main.py
> Added Rotate List Problem

- Binary Tree/Expression Tree/Expression_Tree.cpp
- Binary Tree/Expression Tree/README.md
Added code for the issue #121  Expression Tree from postfix and prefix expression
> Added code for Expression Tree

- String/First Non-Repeating Character/README.md
- String/First Non-Repeating Character/main.py
First Non-Repeating Character description and solution added.
> First Non-Repeating Character

- Array/Heap Sort/Max_heap_sort.cpp
- Array/Heap Sort/README.md
Added code for the issue #123  code for heap sort to sort using max heap
> Code for heap sort to sort using max heap

- Dynamic Programming/Washing Windows/ReadME.md
- Dynamic Programming/Washing Windows/washing_windows.cpp
- Added CPP solution for Washing Windows problem under DP header.
> Added Washing Windows Problem

- Array/Two Sum II - Input array is sorted/Two Sum II - Input array is sorted.cpp
- Array/Two Sum II - Input array is sorted/readme.md
Added Two Sum II - Input array is sorted file to the array folder and also added readme.md file  contain the question in detail
@skully-coder please label it with hacktoberfest
> Two Sum II - Input array is sorted

- Trie/AutoCompletion/AutoCompletion.py
- Trie/AutoCompletion/Readme.md
Added code for the issue #139 Code for AutoCompletion using Trie Data Structure
> Code for AutoCompletion using Trie Data Structure #139

- Array/Sorted Squared Array/Main.cpp
A new main.cpp file addition for more and multi-language solutions
Fixes # (main.cpp)
Added a new .cpp file
> The main.cpp file for sorted_squared_array

- Dynamic Programming/Vacation/README.md
- Dynamic Programming/Vacation/main.cpp
> Added a dynamic programming problem "Vacation" from atcoder

- Linked Lists/Delete Loop/readme.md
> added readme.md for delete loop in linked list

- Array/Circular Queue using Array/Circular_Queue_using_Array.cpp
- Array/Circular Queue using Array/readme.md
Added code for circular queue using array #157 
Fixes #157 
> Code for implementation of circular queue using array. [Fixed length]

- Greedy/Fractional Knapsack/ReadME.md
- Greedy/Fractional Knapsack/fractional_knapsack.cpp
> Added CPP solution for Fractional Knapsack problem under Greedy header.

- Stack/Infix to Postfix and Prefix/Infix_to_postfix_prefix.cpp
- Stack/Infix to Postfix and Prefix/readme.md
converting infix expression to prefix and postfix using stack #156 
Fixes #156 
> converting infix expression to prefix and postfix using stack

- Array/Merge without Extra Space/Merge_without_space.cpp
- Array/Merge without Extra Space/readme.md
code for merging two sorted in sorted order without extra space O(1) #165 
Fixes #165 
> code for merging two sorted in sorted order without extra space O(1)

- Greedy/Coin Problem/readme.md
> added readme.md for coin problem in Greedy

- Array/Snail Sort/README.md
- Array/Snail Sort/main.cpp
Added code for the issue #163  Code for Snail Sort
> Code For Snail Sort #163

- Greedy/Huffman Decoding/ReadME.md
- Greedy/Huffman Decoding/huffman_decoding.cpp
> Added CPP solution for Huffman Decoding problem under Greedy header.

- Array/Matrix Rotation/Matrix_rotation.cpp
- Array/Matrix Rotation/readme.md
Rotate a matrix by 90 degree in clockwise or anticlockwise direction without using any extra space #164 
Fixes #164 
> Rotate a matrix by 90 degree

- Binary Tree/Kth child in Nth Generation/KthChildInNthGeneration.java
- Binary Tree/Kth child in Nth Generation/README.md
In Family of Akaash, every male gives birth to the first Male and then Female whereas each Female gives birth to the first female
then male
We are given nth generation and kth child. We need to find the Gender of the child.
Fixes # (#170)
> Code Added for  Kth Child In Nth Generation in Family Tree

- Array/Chief Hopper/Readme.md
- Array/Chief Hopper/goodlandElectricity.cpp
Hackerrank problem for competitive exams.
> Goodland Electricity

- Stack/Next Greater Element/NextGreaterElement.java
- Stack/Next Greater Element/README.md
Given an array, print the Next Greater Element (NGE) for every element. The Next greater Element for an element x is the first greater element on the right side of x in the array. Elements for which no greater element exist, consider the next greater element as -1.
Fixes # (#189)
> Code added for Next Greater Element in Java [Competitive Programming Problem]

- Math/MillerRabbin_PrimalityTest/MillerRabbin.cpp
Removed redundant code which caused the error and made the rest more self explanatory.
Fixes #113
> Fix #113: CodeFactor issue

- Linked Lists/Merge Two Sorted LL/MergeTwoSortedLL.c
- Linked Lists/Merge Two Sorted LL/README.md
I've added a new problem with a Problem Statement, Explanation, and Code for the Linked List directory.
> I've added Merge Sorted Two Linked Lists to LL Directory

- Array/Rotate Array by K times/main.cpp
- Array/Rotate Array by K times/readme.md
- Array/Rotate Array by K times/solution.cpp
I have added an Optimal Solution with O(n) time complexity and O(1) Space complexity.
Fixes #184 
> Added Optimal solution for rotate array by k itme (issue #184)

- Stack/Nearest Greater Element/README.md
- Stack/Nearest Greater Element/main.cpp
Added solution of Nearest Greater Element problem using stack in cpp.
Fixes #189 
> Added NearestGreaterElement.cpp issue #189

- String/Case Specific Sorting in String/CaseSpecificSortingInString.java
- String/Case Specific Sorting in String/README.md
Given a string S consisting of uppercase and lowercase characters. The task is to sort uppercase and lowercase letters separately such that if the ith place in the original string had an Uppercase character then it should not have a lowercase character after being sorted and vice versa.
Using Heapsort to execute this problem.
Fixes # (#187)
> Code added for Case specific Sorting in String

- Matrix/Matrix Determinant/Matrix-Determinant.py
[Renamed ambiguous variable name l to matrix_size]
> Renamed ambiguous variable name l to matrix_size

- website/src/Category.js
Fixed a Warning related to Whitespaces in "Category" table:
This was probably due to wrong auto-formatting, the formatting style of the `Category.js` also appeared to be different than other pages.
> Fixed a Warning with Whitespaces

- Binary Tree/Add One Row To Tree/README.md
- Binary Tree/Add One Row To Tree/Solution.java
> Add One Row to Tree

- Dynamic Programming/Edit Distance/Edit_Distance.cpp
- Dynamic Programming/Edit Distance/Readme.md
Added Edit Distance Problem in Dynamic Programming Folder
> added edit distance problem

- Linked List/Reverse the LL/README.md
Missing README.md for reversing a linked list. Includes problem statement and explanation of solution
Created README.md for reversing a linked list. Includes problem statement and explanation of solution
> Created README.md for Reversing Linked Lists
